// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//
// IMPORTANT: load .env WITHOUT overriding existing process.env values.
// migrate-test-db.ts passes DATABASE_URL=<TEST_URL> via spawnSync,
// and an unconditional `import 'dotenv/config'` reinstates the
// production URL from .env, silently running migrations against prod.
// override:false guarantees TEST_DATABASE_URL wins when set.
import { config as dotenvConfig } from 'dotenv';
dotenvConfig({ override: false });
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed.ts'
  },
  datasource: {
    url: process.env['DATABASE_URL']!
  }
});
