// Persona harness public types. Reuses assertion vocabulary from
// tests/conversation-fixtures so the two suites speak the same language
// without sharing code. If you add new assertion types here, also
// document them in tests/persona-harness/README.md.

export type AssertionType =
  | 'STAGE_IS'
  | 'STAGE_ADVANCED'
  | 'STEP_IS'
  | 'STEP_REACHED'
  | 'FORBIDDEN_PHRASE_ABSENT'
  | 'PHRASE_PRESENT'
  | 'PHRASE_ABSENT'
  | 'PHRASE_MATCHES'
  | 'AI_MESSAGE_CONTAINS'
  | 'CAPTURED_DATA_HAS'
  | 'CAPTURED_DATA_EQUALS'
  | 'CAPTURED_DATA_VALUE'
  | 'LEAD_INTENT_TAG'
  | 'OUTCOME_IS'
  | 'AI_REPLY_NOT_EMPTY'
  | 'AI_REPLY_MAX_CHARS'
  | 'SCHEDULED_REPLY_EXISTS'
  | 'NOTIFICATION_CREATED'
  | 'NO_QUALITY_GATE_FAILURE'
  | 'NO_TEMPLATE_LEAK'
  | 'NO_FABRICATED_URL'
  | 'LINK_SENT'
  | 'BRANCH_SELECTED'
  | 'BRANCH_HISTORY_HAS_EVENT'
  | 'INBOUND_QUALIFICATION_WRITTEN';

export interface Assertion {
  type: AssertionType;
  value?: unknown;
  // For PHRASE_MATCHES: regex source string
  pattern?: string;
  // For CAPTURED_DATA_*: data point key. `field` is accepted as an
  // alias for ergonomic scenario authoring.
  key?: string;
  field?: string;
  // For LINK_SENT: required URL substring
  urlContains?: string;
  // For BRANCH_* assertions: which script step the event refers to
  step?: number;
  // For BRANCH_HISTORY_HAS_EVENT: event type to find. Accepts the
  // production enum values plus the alias 'step_skipped' which maps
  // to a conditional_skip_decision with skipDecision='skip'.
  eventType?: string;
  // Optional descriptive label for output
  label?: string;
}

export type Turn =
  | { role: 'lead'; content: string }
  | { role: 'assertions'; expect: Assertion[] };

export interface Scenario {
  id: string;
  description?: string;
  fastPath?: boolean; // default true
  expected?: 'pass' | 'fail';
  turns: Turn[];
}

// Subset of AIPersona fields the harness will use to seed. Anything not
// listed becomes default/null.
export interface PersonaSeedConfig {
  personaName: string;
  fullName: string;
  companyName?: string;
  tone?: string;
  systemPrompt: string;
  rawScript?: string;
  qualificationFlow?: string;
  objectionHandling?: string;
  voiceNoteDecisionPrompt?: string;
  qualityScoringPrompt?: string;
  promptConfig?: Record<string, unknown>;
  downsellConfig?: Record<string, unknown>;
  minimumCapitalRequired?: number;
  freeValueLink?: string;
  customPhrases?: Record<string, string>;
  styleAnalysis?: Record<string, unknown> | string;
  // Prod stores these as JSON; can be array or object depending on persona.
  financialWaterfall?: Record<string, unknown> | unknown[];
  knowledgeAssets?: Record<string, unknown> | unknown[];
}

// ─── Prod-dump fixture shapes ───────────────────────────────────────
// Generated by tests/persona-harness/scripts/copy-daetradez-to-test.ts.
// All IDs are placeholder strings ("$ACCOUNT_ID$", "$STEP_3_ID$", ...);
// db-seed.ts substitutes test-harness- prefixed real IDs at seed time
// while preserving FK relationships.

export interface AccountConfigFixture {
  placeholderId: string;
  name: string;
  plan?: string;
  aiProvider?: string;
  awayModeInstagram?: boolean;
  awayModeFacebook?: boolean;
  ghostThresholdDays?: number;
  // Free-form: any other Account fields the copy script captures.
  extras?: Record<string, unknown>;
}

export interface ScriptActionFixture {
  placeholderId: string;
  stepPlaceholderId: string;
  branchPlaceholderId: string | null;
  actionType: string;
  content: string | null;
  linkUrl: string | null;
  linkLabel: string | null;
  formPlaceholderId: string | null;
  voiceNoteRefStripped: boolean; // true if a voiceNoteId was dropped on copy
  bindingMode?: string;
  waitDuration: number | null;
  sortOrder: number;
}

export interface ScriptBranchFixture {
  placeholderId: string;
  stepPlaceholderId: string;
  branchLabel: string;
  conditionDescription: string | null;
  sortOrder: number;
}

export interface ScriptStepFixture {
  placeholderId: string;
  stepNumber: number;
  title: string;
  description: string | null;
  objective: string | null;
  stateKey: string | null;
  requiredDataPoints: unknown;
  recoveryActionType: string | null;
  canonicalQuestion: string | null;
  artifactField: string | null;
  routingRules: unknown;
  completionRule: unknown;
}

export interface ScriptFormFieldFixture {
  placeholderId: string;
  formPlaceholderId: string;
  fieldLabel: string;
  fieldValue: string | null;
  sortOrder: number;
}

export interface ScriptFormFixture {
  placeholderId: string;
  name: string;
  description: string | null;
  fields: ScriptFormFieldFixture[];
}

export interface ScriptFixture {
  placeholderId: string;
  name: string;
  description: string | null;
  isActive: boolean;
  isDefault: boolean;
  createdVia: string;
  originalUploadText: string | null;
  steps: ScriptStepFixture[];
  branches: ScriptBranchFixture[];
  actions: ScriptActionFixture[];
  forms: ScriptFormFixture[];
}

export interface TrainingUploadFixture {
  placeholderId: string;
  fileName: string;
  fileHash: string;
  blobUrl: string;
  rawText: string | null;
  status: string;
  tokenEstimate: number | null;
  conversationCount: number | null;
}

export interface TrainingConversationFixture {
  placeholderId: string;
  uploadPlaceholderId: string;
  leadIdentifier: string;
  outcomeLabel: string;
  contentHash: string;
  messageCount: number;
  closerMessageCount: number;
  leadMessageCount: number;
  voiceNoteCount: number;
  startedAt: string | null;
  endedAt: string | null;
  leadType: string | null;
  primaryObjectionType: string | null;
  dominantStage: string | null;
}

export interface TrainingMessageFixture {
  placeholderId: string;
  conversationPlaceholderId: string;
  sender: 'CLOSER' | 'LEAD' | string;
  text: string | null;
  timestamp: string | null;
  messageType: string;
  stage: string | null;
  objectionType: string | null;
  orderIndex: number;
}

export interface ProdDumpFixture {
  _populated: boolean;
  // Set to a human-readable date string when the copy script runs.
  capturedAt: string | null;
  // Source prod account id (already public — the slug, not a secret).
  sourceAccountIdHash: string;
  accountConfig: AccountConfigFixture;
  personaConfig: PersonaSeedConfig;
  script: ScriptFixture | null;
  trainingUploads: TrainingUploadFixture[];
  trainingConversations: TrainingConversationFixture[];
  trainingMessages: TrainingMessageFixture[];
}

export interface PersonaScenario {
  slug: string;
  description?: string;
  personaConfig: PersonaSeedConfig;
  // Optional prod-dump extras. When provided, db-seed will also seed
  // the Account row, Script + nested rows, and TrainingMessage chain.
  accountConfig?: AccountConfigFixture;
  scriptConfig?: ScriptFixture | null;
  trainingUploads?: TrainingUploadFixture[];
  trainingConversations?: TrainingConversationFixture[];
  trainingMessages?: TrainingMessageFixture[];
  scenarios: Scenario[];
}

export type ScenarioResultStatus =
  | 'PASS'
  | 'FAIL'
  | 'EXPECTED_FAIL'
  | 'RATE_LIMIT_EXHAUSTED'
  | 'HARNESS_ERROR';

export interface AssertionResult {
  assertion: Assertion;
  passed: boolean;
  message: string;
}

export interface TurnResult {
  index: number;
  leadContent: string;
  aiReply: string | null;
  assertions: AssertionResult[];
}

export interface ScenarioResult {
  scenarioId: string;
  status: ScenarioResultStatus;
  elapsedMs: number;
  turns: TurnResult[];
  llmCalls: number;
  costUsd: number;
  error?: string;
}

export interface PersonaResult {
  slug: string;
  scenarios: ScenarioResult[];
  totalElapsedMs: number;
  totalLlmCalls: number;
  totalCostUsd: number;
  providerBreakdown: Record<string, { calls: number; usd: number }>;
}
